#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /
    controller: App\Controller\HomeController::index

database_homepage:
    path: /DB
    controller: App\Controller\Database\DatabaseHomeController::index

cars_homepage:
    path: /DB/CARS
    controller: App\Controller\Cars\CarsHomeController::index

lego_homepage:
    path: /DB/LEGO
    controller: App\Controller\Lego\LegoHomeController::index

kinder_homepage:
    path: /DB/KINDER
    controller: App\Controller\Kinder\KinderHomeController::index

rental_homepage:
    path: /DB/RENTAL
    controller: App\Controller\Rental\RentalHomeController::index

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
