#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /
    controller: App\Controller\HomeController::index

database_homepage:
    path: /DB
    controller: App\Controller\Database\DatabaseHomeController::index

cars_homepage:
    path: /DB/CARS
    controller: App\Controller\Cars\CarsHomeController::index

cars_detail:
    path: /DB/CARS/DETAIL/{plate}
    controller: App\Controller\Cars\CarsHomeController::plate
    defaults:  
        plate: '9209-XF-22' 

lego_homepage:
    path: /DB/LEGO/HOME/{viewFormat}/{rowNumbers}
    controller: App\Controller\Lego\LegoHomeController::index
    defaults:  
        viewFormat: 'table' 
        rowNumbers: 10 

lego_add:
    path: /DB/LEGO/ADD
    controller: App\Controller\Lego\LegoHomeController::add

lego_edit:
    path: /DB/LEGO/EDIT/{pk_name}/{ref}
    controller: App\Controller\Lego\LegoHomeController::edit

lego_delete:
    path: /DB/LEGO/DELETE/{pk_name}/{ref}
    controller: App\Controller\Lego\LegoHomeController::delete

kinder_homepage:
    path: /DB/KINDER
    controller: App\Controller\Kinder\KinderHomeController::index

gifts_homepage:
    path: /DB/GIFTS/HOME/{viewFormat}/{rowNumbers}
    controller: App\Controller\Gifts\GiftsHomeController::index
    defaults:  
        viewFormat: 'table' 
        rowNumbers: 10 


gifts_archivepage:
    path: /DB/GIFTS/ARCHIVEPAGE/{viewFormat}/{rowNumbers}
    controller: App\Controller\Gifts\GiftsHomeController::archive_page
    defaults:  
        viewFormat: 'table' 
        rowNumbers: 10 

gifts_user_add:
    path: /DB/GIFTS/USER/ADD/{user}
    controller: App\Controller\Gifts\GiftsHomeController::user_add
    defaults:  
        user: 'USER'

gifts_userpage:
    path: /DB/GIFTS/USER/{viewFormat}/{rowNumbers}/{user}
    controller: App\Controller\Gifts\GiftsHomeController::user
    defaults:  
        viewFormat: 'table' 
        rowNumbers: 10 
        user: 'USER'

gifts_add:
    path: /DB/GIFTS/ADD
    controller: App\Controller\Gifts\GiftsHomeController::add

gifts_edit:
    path: /DB/GIFTS/EDIT/{pk_name}/{ref}
    controller: App\Controller\Gifts\GiftsHomeController::edit

gifts_archive:
    path: /DB/GIFTS/ARCHIVE/{pk_name}/{ref}
    controller: App\Controller\Gifts\GiftsHomeController::archive

gifts_unarchive:
    path: /DB/GIFTS/UNARCHIVE/{pk_name}/{ref}
    controller: App\Controller\Gifts\GiftsHomeController::unarchive

gifts_delete:
    path: /DB/GIFTS/DELETE/{pk_name}/{ref}
    controller: App\Controller\Gifts\GiftsHomeController::delete

promo_homepage:
    path: /DB/PROMO/HOME/{viewFormat}/{rowNumbers}
    controller: App\Controller\Promo\PromoController::index
    defaults:  
        viewFormat: 'table' 
        rowNumbers: 10 

promo_add:
    path: /DB/PROMO/ADD
    controller: App\Controller\Promo\PromoController::add

promo_edit:
    path: /DB/PROMO/EDIT/{pk_name}/{ref}
    controller: App\Controller\Promo\PromoController::edit

promo_delete:
    path: /DB/PROMO/DELETE/{pk_name}/{ref}
    controller: App\Controller\Promo\PromoController::delete

# gifts_lara:
#     path: /DB/GIFTS/USER/{viewFormat}/{rowNumbers}/{user}
#     controller: App\Controller\Gifts\GiftsHomeController::user
#     defaults:  
#         viewFormat: 'table' 
#         rowNumbers: 10 
#         user: 'LARA'

# gifts_heidi:
#     path: /DB/GIFTS/USER/{viewFormat}/{rowNumbers}/{user}
#     controller: App\Controller\Gifts\GiftsHomeController::user
#     defaults:  
#         viewFormat: 'table' 
#         rowNumbers: 10 
#         user: 'HEIDI'

# gifts_daphne:
#     path: /DB/GIFTS/USER/{viewFormat}/{rowNumbers}/{user}
#     controller: App\Controller\Gifts\GiftsHomeController::user
#     defaults:  
#         viewFormat: 'table' 
#         rowNumbers: 10 
#         user: 'DAPHNE'

# gifts_sabine:
#     path: /DB/GIFTS/USER/{viewFormat}/{rowNumbers}/{user}
#     controller: App\Controller\Gifts\GiftsHomeController::user
#     defaults:  
#         viewFormat: 'table' 
#         rowNumbers: 10 
#         user: 'SABINE'

# gifts_raphael:
#     path: /DB/GIFTS/USER/{viewFormat}/{rowNumbers}/{user}
#     controller: App\Controller\Gifts\GiftsHomeController::user
#     defaults:  
#         viewFormat: 'table' 
#         rowNumbers: 10 
#         user: 'RAPHAEL'

# gifts_maman:
#     path: /DB/GIFTS/USER/{viewFormat}/{rowNumbers}/{user}
#     controller: App\Controller\Gifts\GiftsHomeController::user
#     defaults:  
#         viewFormat: 'table' 
#         rowNumbers: 10 
#         user: 'MAMAN'

# gifts_papa:
#     path: /DB/GIFTS/USER/{viewFormat}/{rowNumbers}/{user}
#     controller: App\Controller\Gifts\GiftsHomeController::user
#     defaults:  
#         viewFormat: 'table' 
#         rowNumbers: 10 
#         user: 'PAPA'

rental_homepage:
    path: /DB/RENTAL
    controller: App\Controller\Rental\RentalHomeController::index

shopping_homepage:
    path: /DB/SHOPPING
    controller: App\Controller\Shopping\ShoppingHomeController::index

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

login_check:
    path: /login_check

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
